#!/usr/bin/env python3
import argparse
import os.path
import shutil
import subprocess
import tarfile
import tempfile
from typing import Optional
from typing import Sequence


# This is a script for generating the tarred resources for git repo
# dependencies.  Currently it's just for "vendoring" ruby support packages.


REPOS = (
    ('rbenv', 'git://github.com/rbenv/rbenv', '0843745'),
    ('ruby-build', 'git://github.com/rbenv/ruby-build', '500863c'),
    (
        'ruby-download',
        'git://github.com/garnieretienne/rvm-download',
        '09bd7c6',
    ),
)


def make_archive(name: str, repo: str, ref: str, destdir: str) -> str:
    """Makes an archive of a repository in the given destdir.

    :param text name: Name to give the archive.  For instance foo.  The file
    that is created will be called foo.tar.gz.
    :param text repo: Repository to clone.
    :param text ref: Tag/SHA/branch to check out.
    :param text destdir: Directory to place archives in.
    """
    output_path = os.path.join(destdir, f'{name}.tar.gz')
    with tempfile.TemporaryDirectory() as tmpdir:
        # Clone the repository to the temporary directory
        subprocess.check_call(('git', 'clone', repo, tmpdir))
        subprocess.check_call(('git', '-C', tmpdir, 'checkout', ref))

        # We don't want the '.git' directory
        # It adds a bunch of size to the archive and we don't use it at
        # runtime
        shutil.rmtree(os.path.join(tmpdir, '.git'))

        with tarfile.open(output_path, 'w|gz') as tf:
            tf.add(tmpdir, name)

    return output_path


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--dest', default='pre_commit/resources')
    args = parser.parse_args(argv)
    for archive_name, repo, ref in REPOS:
        print(f'Making {archive_name}.tar.gz for {repo}@{ref}')
        make_archive(archive_name, repo, ref, args.dest)
    return 0


if __name__ == '__main__':
    exit(main())
