#!/usr/bin/env python
import sys


def main():
    for i in range(6):
        f = sys.stdout if i % 2 == 0 else sys.stderr
        f.write('{}\n'.format(i))
        f.flush()


if __name__ == '__main__':
    exit(main())
